import { Prompt } from "@/interfaces/Prompt";

export const samplePrompts: Prompt[] = [
  {
    id: 1,
    rank: 1,
    title: "The Philosophical Paradox",
    description: "A prompt that explores the famous Ship of Theseus paradox.",
    tags: ["philosophy", "paradox", "thought-experiment"],
    upVotes: 120,
    downVotes: 10,
    userVote: 0,
    isFavorite: false,
    author: "User123",
  },
  {
    id: 2,
    rank: 2,
    title: "The Ultimate Recipe Generator",
    description:
      "This prompt asks the AI to create unique recipes based on the ingredients in your pantry.",
    tags: ["cooking", "AI", "creativity"],
    upVotes: 95,
    downVotes: 5,
    userVote: 1,
    isFavorite: true,
    author: "ChefAI",
  },
  {
    id: 3,
    rank: 3,
    title: "The Time Travel Conundrum",
    description:
      "A narrative prompt challenging the AI to construct a story where time travel creates a closed causal loop.",
    tags: ["science-fiction", "time-travel", "storytelling"],
    upVotes: 87,
    downVotes: 3,
    userVote: -1,
    isFavorite: false,
    author: "SciFiFan42",
  },
  {
    id: 4,
    rank: 4,
    title: "The Haiku Generator",
    description: "A prompt that asks the AI to generate a Haiku poem.",
    tags: ["poetry", "creativity", "haiku"],
    upVotes: 75,
    downVotes: 25,
    userVote: 0,
    isFavorite: false,
    author: "Poet123",
  },
  {
    id: 5,
    rank: 5,
    title: "The Ultimate Recipe Generator",
    description:
      "This prompt asks the AI to create unique recipes based on the ingredients in your pantry.",
    tags: ["cooking", "AI", "creativity"],
    upVotes: 95,
    downVotes: 5,
    userVote: 1,
    isFavorite: true,
    author: "ChefAI",
  },
  {
    id: 6,
    rank: 6,
    title: "The Time Travel Conundrum",
    description:
      "A narrative prompt challenging the AI to construct a story where time travel creates a closed causal loop.",
    tags: ["science-fiction", "time-travel", "storytelling"],
    upVotes: 87,
    downVotes: 3,
    userVote: -1,
    isFavorite: false,
    author: "SciFiFan42",
  },
];
